ALTER TABLE test.users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE test.users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE test.users ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE test.orders ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE test.orders ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE test.orders ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE test.persons ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE test.persons ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE test.persons ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE test.passports ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE test.passports ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE test.passports ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE test.actors ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE test.actors ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE test.actors ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE test.movies ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE test.movies ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE test.movies ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE test.actors_movies ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE test.actors_movies ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE test.actors_movies ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;